version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    restart: unless-stopped

volumes:
  static_volume:
  sqlite_data: