# Generated by Django 5.2.3 on 2025-12-30 00:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_add_system_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Device Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, help_text="Manufacturer's website")),
                ('support_contact', models.CharField(blank=True, help_text='Support contact information', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Device Manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('account_number', models.CharField(blank=True, help_text='Account number with vendor', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Device Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicecategory')),
            ],
            options={
                'verbose_name_plural': 'Device Models',
                'ordering': ['manufacturer', 'model_name'],
                'unique_together': {('manufacturer', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(help_text="Organization's main asset tracking number", max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]+$', 'Asset tag must contain only uppercase letters, numbers, and hyphens')])),
                ('serial_number', models.CharField(help_text="Manufacturer's serial number", max_length=100, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('retired', 'Retired'), ('lost', 'Lost/Stolen'), ('damaged', 'Damaged')], default='available', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IPv4 or IPv6 address', null=True, unique=True)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address in format XX:XX:XX:XX:XX:XX', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$', 'MAC address must be in format XX:XX:XX:XX:XX:XX or XX-XX-XX-XX-XX-XX')])),
                ('usage_type', models.CharField(choices=[('individual', 'Individual'), ('shared', 'Shared')], default='individual', max_length=20)),
                ('shared_usage', models.CharField(blank=True, choices=[('kiosk', 'Kiosk'), ('training', 'Training'), ('shared', 'Shared')], help_text="Required if usage_type is 'shared'", max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('hostname', models.CharField(blank=True, help_text='Device hostname (default: MEX-[last 6 of serial])', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to='employees.employee')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_devices', to=settings.AUTH_USER_MODEL)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicemodel')),
            ],
            options={
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Device Created'), ('assigned', 'Assigned to User'), ('unassigned', 'Unassigned from User'), ('status_change', 'Status Changed'), ('retired', 'Retired'), ('updated', 'Updated')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_history_entries', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='devices.device')),
                ('new_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_device_assignments', to='employees.employee')),
                ('previous_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_device_assignments', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Device Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='devices_dev_device__9c6519_idx'), models.Index(fields=['action', '-created_at'], name='devices_dev_action_9012d7_idx'), models.Index(fields=['created_by', '-created_at'], name='devices_dev_created_323bc5_idx'), models.Index(fields=['device', 'action'], name='devices_dev_device__a0e6a2_idx'), models.Index(fields=['device', 'action', '-created_at'], name='devices_dev_device__ab77af_idx'), models.Index(fields=['previous_status', 'new_status'], name='devices_dev_previou_40cf80_idx'), models.Index(fields=['new_status', '-created_at'], name='devices_dev_new_sta_dbe069_idx'), models.Index(fields=['new_employee', '-created_at'], name='devices_dev_new_emp_bf48f9_idx'), models.Index(fields=['previous_employee', '-created_at'], name='devices_dev_previou_d2943d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['assigned_to'], name='devices_dev_assigne_2d4166_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_model'], name='devices_dev_device__629817_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['created_at'], name='devices_dev_created_f36e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status', 'assigned_to'], name='devices_dev_status_698348_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status', 'device_model'], name='devices_dev_status_6a7a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_model', 'status'], name='devices_dev_device__16c8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['assigned_to', 'status'], name='devices_dev_assigne_2a1355_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['asset_tag'], name='devices_dev_asset_t_9e2c54_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='devices_dev_serial__4a3e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['location'], name='devices_dev_locatio_c16132_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['hostname'], name='devices_dev_hostnam_7489a0_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['ip_address'], name='devices_dev_ip_addr_477d04_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['mac_address'], name='devices_dev_mac_add_307aef_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['usage_type'], name='devices_dev_usage_t_b9ee29_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['shared_usage'], name='devices_dev_shared__666850_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['usage_type', 'shared_usage'], name='devices_dev_usage_t_ad03d1_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['assigned_date'], name='devices_dev_assigne_1e795d_idx'),
        ),
    ]
