# Generated by Django 5.2.1 on 2025-06-15 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status"], name="devices_dev_status_bbf58f_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["assigned_to"], name="devices_dev_assigne_2d4166_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_model"], name="devices_dev_device__629817_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["created_at"], name="devices_dev_created_f36e7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["status", "assigned_to"], name="devices_dev_status_698348_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["status", "device_model"], name="devices_dev_status_6a7a8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_model", "status"], name="devices_dev_device__16c8c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["assigned_to", "status"], name="devices_dev_assigne_2a1355_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["asset_tag"], name="devices_dev_asset_t_9e2c54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["serial_number"], name="devices_dev_serial__4a3e3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["location"], name="devices_dev_locatio_c16132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["assigned_date"], name="devices_dev_assigne_1e795d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["purchase_date"], name="devices_dev_purchas_0816db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["warranty_expiry"], name="devices_dev_warrant_74a51e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicehistory",
            index=models.Index(
                fields=["device", "-created_at"], name="devices_dev_device__9c6519_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicehistory",
            index=models.Index(
                fields=["action", "-created_at"], name="devices_dev_action_9012d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicehistory",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="devices_dev_created_323bc5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicehistory",
            index=models.Index(
                fields=["device", "action"], name="devices_dev_device__a0e6a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicehistory",
            index=models.Index(
                fields=["device", "action", "-created_at"],
                name="devices_dev_device__ab77af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicehistory",
            index=models.Index(
                fields=["previous_status", "new_status"],
                name="devices_dev_previou_40cf80_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicehistory",
            index=models.Index(
                fields=["new_status", "-created_at"],
                name="devices_dev_new_sta_dbe069_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicehistory",
            index=models.Index(
                fields=["new_user", "-created_at"],
                name="devices_dev_new_use_e621c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicehistory",
            index=models.Index(
                fields=["previous_user", "-created_at"],
                name="devices_dev_previou_69633a_idx",
            ),
        ),
    ]
