# Generated by Django 5.2.3 on 2026-01-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='device',
            name='devices_dev_locatio_c16132_idx',
        ),
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
    ]
