# Generated by Django 5.2.1 on 2025-06-15 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_device_devices_dev_status_bbf58f_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicemodel",
            options={
                "ordering": ["manufacturer", "model_name"],
                "verbose_name_plural": "Device Models",
            },
        ),
    ]
