# Generated by Django 5.2.3 on 2026-02-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_device_devices_dev_locatio_c16132_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='general_spec_groups',
            field=models.JSONField(blank=True, default=list, help_text='List of general specification groups enabled for this category'),
        ),
    ]
