# Generated by Django 5.2.3 on 2025-07-09 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_alter_devicemodel_options"),
        ("employees", "0003_alter_employee_work_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="devicehistory",
            name="devices_dev_new_use_e621c9_idx",
        ),
        migrations.RemoveIndex(
            model_name="devicehistory",
            name="devices_dev_previou_69633a_idx",
        ),
        migrations.RemoveField(
            model_name="devicehistory",
            name="new_user",
        ),
        migrations.RemoveField(
            model_name="devicehistory",
            name="previous_user",
        ),
        migrations.AddField(
            model_name="device",
            name="building",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="device",
            name="floor",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="device",
            name="hostname",
            field=models.CharField(
                blank=True, help_text="Computer name or hostname", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IPv4 or IPv6 address", null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="mac_address",
            field=models.CharField(
                blank=True,
                help_text="MAC address in format XX:XX:XX:XX:XX:XX",
                max_length=17,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$",
                        "MAC address must be in format XX:XX:XX:XX:XX:XX or XX-XX-XX-XX-XX-XX",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="room",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="device",
            name="shared_usage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kiosk", "Kiosk"),
                    ("training", "Training"),
                    ("shared", "Shared"),
                ],
                help_text="Required if usage_type is 'shared'",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="usage_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("shared", "Shared")],
                default="individual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="devicehistory",
            name="new_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_device_assignments",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="devicehistory",
            name="previous_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_device_assignments",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_devices",
                to="employees.employee",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["building"], name="devices_dev_buildin_c6619a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["hostname"], name="devices_dev_hostnam_7489a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["ip_address"], name="devices_dev_ip_addr_477d04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["mac_address"], name="devices_dev_mac_add_307aef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["usage_type"], name="devices_dev_usage_t_b9ee29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["shared_usage"], name="devices_dev_shared__666850_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["usage_type", "shared_usage"],
                name="devices_dev_usage_t_ad03d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["building", "floor", "room"],
                name="devices_dev_buildin_8e465e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicehistory",
            index=models.Index(
                fields=["new_employee", "-created_at"],
                name="devices_dev_new_emp_bf48f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicehistory",
            index=models.Index(
                fields=["previous_employee", "-created_at"],
                name="devices_dev_previou_d2943d_idx",
            ),
        ),
    ]
