# Generated by Django 5.2.3 on 2026-02-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_add_category_general_spec_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='is_general',
            field=models.BooleanField(default=False, help_text='Mark this category as a general specification category'),
        ),
        migrations.AddField(
            model_name='devicecategory',
            name='specifications',
            field=models.JSONField(blank=True, default=list, help_text='List of custom specification field definitions for this category'),
        ),
    ]
