# Generated by Django 5.2.3 on 2025-07-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "devices",
            "0004_remove_devicehistory_devices_dev_new_use_e621c9_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, help_text="Manufacturer's website")),
                ('support_contact', models.CharField(blank=True, help_text='Support contact information', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Device Manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('account_number', models.CharField(blank=True, help_text='Account number with vendor', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Device Vendors',
                'ordering': ['name'],
            },
        ),
    ]
