# Generated by Django 5.2.1 on 2025-07-27 04:01

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_auto_20250716_1819"),
        ("employees", "0004_alter_jobtitle_options_remove_employee_building_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="device",
            name="devices_dev_buildin_c6619a_idx",
        ),
        migrations.RemoveIndex(
            model_name="device",
            name="devices_dev_buildin_8e465e_idx",
        ),
        migrations.RemoveField(
            model_name="device",
            name="building",
        ),
        migrations.RemoveField(
            model_name="device",
            name="floor",
        ),
        migrations.AddField(
            model_name="device",
            name="it_asset_tag",
            field=models.CharField(
                blank=True,
                help_text="IT department specific asset tag",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="asset_tag",
            field=models.CharField(
                help_text="Organization's main asset tracking number",
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z0-9-]+$",
                        "Asset tag must contain only uppercase letters, numbers, and hyphens",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="room",
            field=models.CharField(
                blank=True, help_text="Specific room within the location", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="serial_number",
            field=models.CharField(
                help_text="Manufacturer's serial number", max_length=100, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["location", "room"], name="devices_dev_locatio_bc454a_idx"
            ),
        ),
    ]
