# Generated by Django 5.2.3 on 2025-10-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_fix_remaining_power_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('retired', 'Retired'), ('lost', 'Lost/Stolen'), ('damaged', 'Damaged')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='action',
            field=models.CharField(choices=[('created', 'Device Created'), ('assigned', 'Assigned to User'), ('unassigned', 'Unassigned from User'), ('status_change', 'Status Changed'), ('retired', 'Retired'), ('updated', 'Updated')], max_length=20),
        ),
    ]
