# Generated by Django 5.2.3 on 2025-10-31 03:29

from django.db import migrations, models


def copy_it_asset_tag_to_hostname(apps, schema_editor):
    """Copy it_asset_tag values to hostname field before removing it_asset_tag"""
    Device = apps.get_model('devices', 'Device')
    for device in Device.objects.all():
        if device.it_asset_tag and not device.hostname:
            device.hostname = device.it_asset_tag
            device.save(update_fields=['hostname'])


def reverse_copy(apps, schema_editor):
    """Reverse migration - copy hostname back to it_asset_tag"""
    Device = apps.get_model('devices', 'Device')
    for device in Device.objects.all():
        if device.hostname and not device.it_asset_tag:
            device.it_asset_tag = device.hostname
            device.save(update_fields=['it_asset_tag'])


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_device_status_alter_devicehistory_action'),
    ]

    operations = [
        # Step 1: Copy it_asset_tag to hostname
        migrations.RunPython(copy_it_asset_tag_to_hostname, reverse_copy),

        # Step 2: Remove it_asset_tag field
        migrations.RemoveField(
            model_name='device',
            name='it_asset_tag',
        ),

        # Step 3: Make hostname unique
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, help_text='Device hostname (default: MEX-[last 6 of serial])', max_length=100, null=True, unique=True),
        ),
    ]
