# Generated by Django 5.2.3 on 2025-07-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_separate_users_employees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="work_email",
            field=models.EmailField(
                blank=True,
                help_text="Different from personal email if needed",
                max_length=254,
            ),
        ),
    ]
