# Generated by Django 5.2.3 on 2026-01-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_add_system_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
    ]
