# Generated by Django 5.2.1 on 2025-07-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_alter_employee_work_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobtitle",
            options={"ordering": ["title"], "verbose_name_plural": "Job Titles"},
        ),
        migrations.RemoveField(
            model_name="employee",
            name="building",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="floor",
        ),
        migrations.AlterField(
            model_name="employee",
            name="desk_number",
            field=models.CharField(
                blank=True,
                help_text="Desk/cubicle number within the location",
                max_length=20,
            ),
        ),
    ]
