# Generated by Django 5.2.3 on 2026-02-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_department_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_department_responsible',
            field=models.BooleanField(default=False, help_text='Designate this employee as the responsible person for their department'),
        ),
    ]
