# Generated by Django 5.2.3 on 2025-10-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_jobtitle_options_remove_employee_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, help_text="Employee position/title in the organization", max_length=100),
        ),
    ]
