# Generated by Django 5.2.3 on 2025-07-09 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_update_user_roles"),
        ("employees", "0003_alter_employee_work_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.RemoveField(
            model_name="user",
            name="employee_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active_employee",
        ),
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="user",
            name="linked_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to employee record if this user represents a specific employee",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.employee",
            ),
        ),
    ]
