# Generated by Django 5.2.3 on 2025-07-10 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_user_department_remove_user_employee_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuickAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_code",
                    models.CharField(
                        choices=[
                            ("add_device", "Add Device"),
                            ("assign_device", "Assign Device"),
                            ("return_device", "Return Device"),
                            ("quick_search", "Quick Search"),
                            ("add_user", "Add User"),
                            ("add_employee", "Add Employee"),
                            ("manage_employees", "Manage Employees"),
                            ("generate_report", "Generate Report"),
                            ("approvals", "View Approvals"),
                            ("bulk_operations", "Bulk Operations"),
                        ],
                        max_length=50,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "action_code"],
                "unique_together": {("user", "action_code")},
            },
        ),
    ]
