# Generated by Django 5.2.3 on 2025-07-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userquickaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
