# Generated by Django 5.2.3 on 2025-07-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_manage_employees_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquickaction",
            name="action_code",
            field=models.CharField(
                choices=[
                    ("add_device", "Add Device"),
                    ("assign_device", "Assign Device"),
                    ("return_device", "Return Device"),
                    ("request_maintenance", "Request Maintenance"),
                    ("quick_search", "Quick Search"),
                    ("add_user", "Add User"),
                    ("add_employee", "Add Employee"),
                    ("generate_report", "Generate Report"),
                    ("approvals", "View Approvals"),
                    ("bulk_operations", "Bulk Operations"),
                ],
                max_length=50,
            ),
        ),
    ]
