# Generated by Django 5.2.3 on 2025-07-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_request_maintenance_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_change_required",
            field=models.BooleanField(
                default=False, help_text="Force user to change password on next login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user last changed their password",
                null=True,
            ),
        ),
    ]
