# Generated by Django 5.2.3 on 2025-07-22 20:48

from django.db import migrations


def remove_bulk_operations_quick_actions(apps, schema_editor):
    """Remove bulk_operations quick actions from all users"""
    UserQuickAction = apps.get_model('core', 'UserQuickAction')
    UserQuickAction.objects.filter(action_code='bulk_operations').delete()


def reverse_remove_bulk_operations_quick_actions(apps, schema_editor):
    """This migration is not reversible since we don't want to restore bulk operations"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_user_password_change_required_and_more"),
    ]

    operations = [
        migrations.RunPython(
            remove_bulk_operations_quick_actions,
            reverse_remove_bulk_operations_quick_actions
        ),
    ]
