# Generated by Django 5.2.1 on 2025-07-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20250722_2048"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Location name (e.g., 'Main Office', 'Remote', 'Building A - Floor 2')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for location (e.g., 'MAIN', 'REMOTE', 'BA-F2')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details about this location"
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Physical address if applicable"
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, help_text="Building identifier", max_length=50
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True, help_text="Floor number/identifier", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Locations",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="userquickaction",
            name="action_code",
            field=models.CharField(
                choices=[
                    ("add_device", "Add Device"),
                    ("assign_device", "Assign Device"),
                    ("return_device", "Return Device"),
                    ("request_maintenance", "Request Maintenance"),
                    ("quick_search", "Quick Search"),
                    ("add_user", "Add User"),
                    ("add_employee", "Add Employee"),
                    ("generate_report", "Generate Report"),
                    ("approvals", "View Approvals"),
                ],
                max_length=50,
            ),
        ),
    ]
