# Generated by Django 5.2.3 on 2025-10-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_location_alter_userquickaction_action_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquickaction',
            name='action_code',
            field=models.CharField(choices=[('add_device', 'Add Device'), ('assign_device', 'Assign Device'), ('return_device', 'Return Device'), ('quick_search', 'Quick Search'), ('add_user', 'Add User'), ('add_employee', 'Add Employee'), ('generate_report', 'Generate Report'), ('approvals', 'View Approvals')], max_length=50),
        ),
    ]
