# Generated by Django 5.2.3 on 2025-12-30 00:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('devices', '0001_initial'),
        ('employees', '0002_add_system_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('pending_return', 'Pending Return'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='active', max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('return_notes', models.TextField(blank=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_assignments', to='approvals.approvalrequest')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices_by', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='devices.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='employees.employee')),
            ],
            options={
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['device', 'status'], name='assignments_device__735190_idx'), models.Index(fields=['employee', '-assigned_date'], name='assignments_employe_714756_idx'), models.Index(fields=['status', '-assigned_date'], name='assignments_status_6884c6_idx'), models.Index(fields=['assigned_by', '-assigned_date'], name='assignments_assigne_5a0a41_idx'), models.Index(fields=['device', 'status', 'employee'], name='assignments_device__345c8c_idx'), models.Index(fields=['employee', 'status'], name='assignments_employe_cc33f5_idx'), models.Index(fields=['assigned_date'], name='assignments_assigne_04515d_idx'), models.Index(fields=['expected_return_date'], name='assignments_expecte_9febcb_idx'), models.Index(fields=['actual_return_date'], name='assignments_actual__b8b21f_idx'), models.Index(fields=['status', 'expected_return_date'], name='assignments_status_3e8c41_idx'), models.Index(fields=['status', 'actual_return_date'], name='assignments_status_8ccd8e_idx'), models.Index(fields=['created_at'], name='assignments_created_300492_idx')],
            },
        ),
    ]
