# Generated by Django 5.2.1 on 2025-06-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="condition_at_assignment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="condition_at_return",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                ],
                max_length=20,
            ),
        ),
    ]
