# Generated by Django 5.2.1 on 2025-06-15 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_alter_assignment_condition_at_assignment_and_more"),
        ("devices", "0002_device_devices_dev_status_bbf58f_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["device", "status"], name="assignments_device__735190_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["user", "-assigned_date"], name="assignments_user_id_7bfa4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["status", "-assigned_date"],
                name="assignments_status_6884c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["assigned_by", "-assigned_date"],
                name="assignments_assigne_5a0a41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["device", "status", "user"],
                name="assignments_device__eeeacd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["user", "status"], name="assignments_user_id_98b760_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["assigned_date"], name="assignments_assigne_04515d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["expected_return_date"], name="assignments_expecte_9febcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["actual_return_date"], name="assignments_actual__b8b21f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["status", "expected_return_date"],
                name="assignments_status_3e8c41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["condition_at_assignment"],
                name="assignments_conditi_0466e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["condition_at_return"], name="assignments_conditi_bd4987_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["status", "actual_return_date"],
                name="assignments_status_8ccd8e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["created_at"], name="assignments_created_300492_idx"
            ),
        ),
    ]
