# Generated by Django 5.2.1 on 2025-06-15 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
        ("assignments", "0004_assignment_assignments_device__735190_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="approval_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completed_assignments",
                to="approvals.approvalrequest",
            ),
        ),
    ]
