# Generated by Django 5.2.3 on 2025-07-09 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_assignment_approval_request"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='device_assignments',
                to='employees.employee',
                null=True,
            ),
        ),
        migrations.RunSQL(
            "UPDATE assignments_assignment SET employee_id = user_id;",
            reverse_sql="UPDATE assignments_assignment SET user_id = employee_id;"
        ),
        migrations.AlterField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='device_assignments',
                to='employees.employee',
            ),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-assigned_date']},
        ),
    ]
