# Generated by Django 5.2.3 on 2025-07-21 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0002_add_device_return_request_type"),
        ("assignments", "0006_auto_20250709_2028"),
        ("devices", "0005_auto_20250716_1819"),
        ("employees", "0003_alter_employee_work_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assignment",
            name="assignments_user_id_7bfa4c_idx",
        ),
        migrations.RemoveIndex(
            model_name="assignment",
            name="assignments_device__eeeacd_idx",
        ),
        migrations.RemoveIndex(
            model_name="assignment",
            name="assignments_user_id_98b760_idx",
        ),
        migrations.RenameField(
            model_name="maintenancerequest",
            old_name="vendor",
            new_name="preferred_vendor",
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="additional_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="affected_component",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="business_impact",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_impact", "No Impact - Cosmetic only"),
                    ("low_impact", "Low Impact - Minor inconvenience"),
                    ("medium_impact", "Medium Impact - Affects productivity"),
                    ("high_impact", "High Impact - Significantly impairs work"),
                    ("critical_impact", "Critical - Cannot perform job functions"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="downtime_window",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_preference", "No Preference"),
                    ("business_hours", "Business Hours (9 AM - 5 PM)"),
                    ("after_hours", "After Hours (5 PM - 9 AM)"),
                    ("weekends", "Weekends Only"),
                    ("emergency", "Emergency - Any Time"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="issue_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hardware_failure", "Hardware Failure"),
                    ("software_issue", "Software Issue"),
                    ("performance", "Performance Problem"),
                    ("connectivity", "Connectivity Issue"),
                    ("physical_damage", "Physical Damage"),
                    ("upgrade_request", "Upgrade Request"),
                    ("cleaning", "Cleaning Required"),
                    ("replacement_parts", "Replacement Parts"),
                    ("preventive", "Preventive Maintenance"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="requested_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="steps_to_reproduce",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="users_affected",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["employee", "-assigned_date"],
                name="assignments_employe_714756_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["device", "status", "employee"],
                name="assignments_device__345c8c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["employee", "status"], name="assignments_employe_cc33f5_idx"
            ),
        ),
    ]
