# Generated by Django 5.2.3 on 2025-10-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_remove_assignment_assignments_user_id_7bfa4c_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
