# Generated by Django 5.2.3 on 2025-07-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("device_assignment", "Device Assignment"),
                    ("device_return", "Device Return"),
                    ("device_transfer", "Device Transfer"),
                    ("bulk_operation", "Bulk Operation"),
                    ("extended_assignment", "Extended Assignment"),
                ],
                max_length=50,
            ),
        ),
    ]
